title:              CBC - blog
email:              your-email@example.com
description:        ğ—šğ—²ğ—ºğ—²ğ—¶ğ—»ğ˜€ğ—®ğ—º ğ—¹Ã¶ğ˜€ğ—²ğ—» ğ˜„ğ—¶ğ—¿ ğ—±ğ—®ğ˜€ ğ—ğ—¼ğ—ºğ—½ğ—¹ğ—²ğ˜…ğ—²
author:             CBC
baseurl:            "/"
url:                "https://crack-brained.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
